Links2004/arduinoWebSockets

src/WebSocketsServer.cpp

Some websocket clients use "Upgrade: WebSocket" instead of "Upgrade: websocket" in the GET request header.  This patch adds an extra case to handle that.

Add case for 'Upgrade: WebSocket'

---

src/WebSockets.h
src/WebSocketsClient.cpp
src/WebSocketsClient.h

Add the possibility to define subprotocol in websocket client. If not defined "arduino" is still used.
Not an experient coder, but I believe the changes make it  backwards compatible with code already written.

add possibilty to define subprotocol of websockets client

---

src/WebSocketsClient.cpp

Some server implementations (e.g. slack bots api) don't accept the connection if `Sec-WebSocket-Protocol` is specified.

Make the `Sec-WebSocket-Protocol` header optional

---

src/WebSockets.h
src/WebSocketsClient.cpp

Hi Markus,
Firstly thanks for this great library. I have made two changes and was hoping you could merge them into your library:
1. I adopted the change you had already made for the "Upgrade" header to the "Connection" header. I looked at the RFC and Upgrade with upper case should be the expected value, but there seems to be a lot of "broken" servers out there (for instance everything based on TomCat) that send a lower case upgrade. the equalsIgnoreCase should work with both and make your library work with all servers. 
2. I changed the behavior of the setAuthorization(const char * auth) function. In the original you just took the passed value and appended it unmodified to the Authorization header, but it still had the BASIC in front of it. Therefore it would still only allow basic …

Compatibility for broken servers and additional authentication option instead of just basic

---

src/WebSocketsClient.cpp

Added the port number to Host, which is required when the port is not 80 or 443.
Also added Origin.  Without it some WebSocket Servers will fail the handshake.  This should probably be user configurable.

Adjustments to headers during client handshake.

---

src/WebSocketsServer.cpp

This is a case sensitivity fix for the Connection header Upgrade value to make this part meet the requirement of IETF websocket RFC 6455 4.2.1.4: "A |Connection| header field that includes the token "Upgrade", treated as an ASCII case-insensitive value."

RFC 6455 4.2.1.4 case sensitivity fix

---

examples/Nginx/esp8266.ssl.reverse.proxy.conf

New esp8266.ssl.reverse.proxy.conf nginx SSL reverse proxy configuration file dropped into the new /examples/Nginx/ folder

Added sample ESP8266 nginx SSL reverse proxy configuration file

---

src/WebSockets.h

Making possible to define WEBSOCKETS_NETWORK_TYPE as a compile parameter.

WEBSOCKETS_NETWORK_TYPE exteral definition

---

examples/WebSocketClientSocketIO/WebSocketClientSocketIO.ino
src/WebSockets.cpp
src/WebSockets.h
src/WebSocketsClient.cpp
src/WebSocketsClient.h

I needed a websocket client able to communicate with a socket.io server so I modified the handshake to be compatible for socket.io server.

Add socket.io client

---

src/WebSocketsServer.h

This allows classes inheriting from it to call sendFrame with custom
arguments.
This is useful for example to implement continuation frames support, like in this [example](https://gist.github.com/nerochiaro/6d5ad350ad6c094c21b6cd02c48c67e3)

Change inheritance of WebSocketServer

---

src/WebSocketsClient.cpp

- Remove duplicate handshake headers
- Add debug log for displaying handshake headers
Host, Origin, and User-Agent were duplicated in the case the client was
not socketIO or if it was and has a sessionId

Remove duplicate handshake headers

---

README.md
examples/ParticleWebSocketClient/application.cpp
src/WebSockets.cpp
src/WebSockets.h
src/WebSocketsClient.cpp
src/WebSocketsClient.h
src/WebSocketsServer.cpp
src/WebSocketsServer.h

Added a few defines to use Particle-specific functions and classes

Make library compatible with Particle devices

---

examples/WebSocketClientSockJsAndStomp/WebSocketClientSockJsAndStomp.ino
src/WebSockets.h
src/WebSocketsClient.cpp
src/WebSocketsClient.h

Hi, I had an issue with connecting to a [Spring based SockJS+STOMP endpoint](https://docs.spring.io/spring/docs/current/spring-framework-reference/html/websocket.html). Specifically the default settings of Spring do not allow an "Origin" header which is hardcoded in the current version of the arduinoWebSockets library. Also, there was no example how to handle SockJS+STOMP.
This pull request adds the capability of removing the hardcoded "Origin" header and enables the user to set custom headers. Additionally it provides an example for connecting to a Spring based SockJS+STOMP endpoint.
There are probably ways to do this more elegantly (like using String arrays to specify headers) or efficiently (e.g., using preprocessor statements), but I opted for the fasted way to implement this. Let me …

Extra headers (including removal of "Origin") and SockJS+STOMP example

---

examples/WebSocketClientStomp/WebSocketClientStomp.ino
examples/WebSocketClientStompOverSockJs/WebSocketClientStompOverSockJs.ino

Making a plain STOMP connection work (without SockJS, cf. #216) was a little tricky since STOMP messages are NULL terminated. That is, _arduinoWebSockets_ determines the payload length via `std::strlen()` thus dropping the required NULL character. The solution is to pass the incremented (+1) length of a NULL terminated String instead of its original length. While this seems obvious, for me, it took some time to figure this out. I added an example to keep others from spending as much time one this as I did ;)

Add example for plain STOMP connection

---

src/WebSockets.h

without these definitions I'd got the error, when I tried to use templates in my project:
`.pioenvs\d1_mini\lib9ab\libWebSockets_ID549.a(WebSocketsServer.cpp.o):(.rodata._ZTI16WebSocketsServer[_ZTI16WebSocketsServer]+0x10): undefined reference to `typeinfo for WebSockets'
collect2.exe: error: ld returned 1 exit status`

fix undefined virtual methods

---

src/WebSockets.cpp
src/WebSocketsClient.cpp

Debug prints cause a lot of compile error on ESP32 due to incorrect format specifiers. This commit fixes these.

Fix format specifiers

---

src/WebSockets.cpp
src/WebSockets.h
src/WebSocketsClient.cpp
src/WebSocketsServer.cpp

wasn't able to test. Hoping for CI to test it. Please let me know if any changes required.

make masking RFC complaint and fix #208

---

examples/esp8266/WebSocketClient/WebSocketClient.ino
library.json
library.properties
src/WebSockets.cpp
src/WebSockets.h
src/WebSocketsClient.cpp
src/WebSocketsClient.h

1. automatic WS-client heartbeat (ping/pong based)
1. sending ping in specified intervals
1. expecting pong within specified interval
1. if no pong received specified number of times - consider disconnected
Well, there is one issue with specifying that number of times for disconnect:
Client will try sending pings and if it reaches some threshold (tcp tx buffer?) sendPing can stay "frozen" until tcp times out... But 1-2 is OK.

Implementing automatic WS client-side heartbeat

---

src/SocketIOclient.cpp
src/WebSocketsServer.cpp

Fix : warning: enumeration value 'WStype_ERROR' not handled in switch [-Wswitch]
Fix : warning: variable 'ip' set but not used [-Wunused-but-set-variable]

Fix warnings in platformIO

---

src/WebSockets.cpp

if data isn't available yet, but is expected, yielding here is nicer
than burning the cpu in a loop, just like in esp8266 case.

add a yield here for esp32 to avoid a busy loop

---

src/WebSocketsServer.cpp
src/WebSocketsServer.h

Heartbeat Feature was already implemented for WebSocketsClient. The Feature is now transfered to WebSocketsServer, so it can be detected, if the client is responsive.
See pull request #383.

Implementing automatic WS server-side heartbeat

---

src/WebSocketsClient.cpp

This allows `setReconnectInterval()` to be called before `begin()` and stops `begin()` from overriding `_reconnectInterval` every time it is called.

Initialize _reconnectInterval in constructor.

---

src/WebSocketsClient.cpp
src/WebSocketsClient.h

Fixes issue #564 .
Timeout added to disconnect if server doesn't respond in `WSC_HEADER `state.

header response timeout added

---

src/WebSocketsClient.cpp

Hi,
I'm having trouble with SSL Connection with sockets.streamlabs.com using fingerprint, I found that no fingerprint is passed to WiFiClientSecure so the check break up.
I'm using [SocketIoClient](https://github.com/timum-viw/socket.io-client) and my piece of code is:
```c
webSocket.beginSSL("sockets.streamlabs.com", 443, <query_parameters>, "E7 93 77 36 DA D4 15 0F C1 C1 8F 14 D5 2A C8 72 93 D0 6F 2A");
```
And I receive this log error on connection:
```
[WS-Client] connect wss...
[hostByName] request IP for: sockets.streamlabs.com
[hostByName] Host: sockets.streamlabs.com IP: 3.136.243.104
:ref 1
BSSL:_connectSSL: start connection
BSSL:Connection *will* fail, no authentication method is setup
:wr 227 0
:wrc 227 227 0
:ack 227
:rn 536
:rch 536, 536
:rd 5, 1072, 0
:rdi 536, 5
:rch 1072, …
```

setFingerprint in WiFiClientSecure required to pass certificate Check

---

src/WebSockets.cpp
src/WebSockets.h
src/WebSocketsServer.cpp

flush causes a bunch of reads as we try to close the socket on esp32. I
think flush is broken on that platform. the comments indicate confusion.
added some debug logs for important cases that were missing them, some
missing newlines to existing logs.
added a longer yield when waiting for data, in some super busy cases it
could trigger a task watchdog or otherwise starve the system. (yield
alone doesn't always switch to lower priority tasks)
make some other yields conditional to avoid some waste when it would
double-yield.

avoid flush on esp32, add/fix debugs, longer yield when waiting for data

---

examples/esp8266/WebSocketClientSSLWithCA/WebSocketClientSSLWithCA.ino

This PR adds a example showing how to begin SSL websockets when using a TLS/SSL certificate for server validation. It uses `wss://echo.websocket.org/` as endpoint to have a readily available TLS server with a known certificate.
This example is mostly based on the one in [examples/esp8266/WebSocketClientSSL](https://github.com/Links2004/arduinoWebSockets/blob/master/examples/esp8266/WebSocketClientSSL/WebSocketClientSSL.ino)

Add example for SSL websocket with CA certificate

---

examples/esp8266/WebSocketClientSSLWithCA/WebSocketClientSSLWithCA.ino
src/SocketIOclient.cpp
src/SocketIOclient.h
src/WebSocketsClient.cpp
src/WebSocketsClient.h

Allows WiFiClientSecureBearSSL users to use client certificate and private key for the WebSocket.
Added a commented example in WebSocketClientSSLWithCA.ino.
Also added functions to SocketIOclient: beginSSL() , beginSslWithCA etc. which seem to be missing (written in WebSocketsClient but not used in SocketIOclient).

Add SSL client certificate support

---

src/WebSocketsClient.cpp

Closes https://github.com/Links2004/arduinoWebSockets/issues/577

Fix for Newline in Headers when extraHeaders is Empty [577]

---

src/WebSockets.h
src/WebSockets4WebServer.h
src/WebSocketsServer.cpp

Reference: [discussion](https://github.com/Links2004/arduinoWebSockets/pull/575#issuecomment-720613241) with @mcspr
(opened to discussion or any other solution)

fix WSclient_t initialization in server

---

src/WebSockets.cpp

To fix [**warning sha.h is deprecated, use sha_parallel_engine.h** #738](https://github.com/Links2004/arduinoWebSockets/issues/738)

Suppress `esp32/sha.h` warning

---

src/WebSocketsServer.cpp

```
WebSocketsServer.cpp: In member function 'WSclient_t* WebSocketsServerCore::handleNewClient(WiFiClient*)':
WebSocketsServer.cpp:634:12: warning: function may return address of local variable [-Wreturn-local-addr]
return client;
^~~~~~
WebSocketsServer.cpp:626:20: note: declared here
WSclient_t dummy = WSclient_t();
```
If the check in line 615 is true, the address of a local variable is returned. 
This commit prevents this and thus avoids the compiler warning.

Fix compiler warning "function may return address of local variable"

---

src/WebSockets.cpp

This PR fixes a crash which occurs for small input lengths of the `base64_encode` function.
For a very small `auth` (length < 3), the `base64_encode` function fails when reaching the following line:
https://github.com/Links2004/arduinoWebSockets/blob/751cf87b6cd684c9d339f0314a18b0ee866d449c/src/WebSockets.cpp#L582C22-L582C22
This is the error message on the console:
```
CORRUPT HEAP: Bad tail at 0x3ffbdb1c. Expected 0xbaad5678 got 0xbaad5600
assert failed: multi_heap_free multi_heap_poisoning.c:253 (head != NULL)
```
Probably it is due to a buffer overflow. With a minimum buffer size of 5, this crash doesn't occur anymore.
To test the fix, I called `WebSocketsClient::setAuthorization(const char * user, const char * password)` with user `""` and password `"b"`.
Btw. and thanks for …

Avoid buffer overflow for small Basic Authentication header

---

examples/esp32_pio/CustomNetworkClient/.clang-format
examples/esp32_pio/CustomNetworkClient/.gitignore
examples/esp32_pio/CustomNetworkClient/platformio.ini
examples/esp32_pio/CustomNetworkClient/readme.md
examples/esp32_pio/CustomNetworkClient/src/main.cpp
examples/esp32_pio/CustomNetworkClient/src/network_client.cpp
examples/esp32_pio/CustomNetworkClient/src/network_client_impl.cpp
examples/esp32_pio/CustomNetworkClient/src/network_client_impl.h
examples/esp32_pio/CustomNetworkClient/src/network_client_secure.cpp
src/NetworkClient.h
src/NetworkClientSecure.h
src/WebSockets.h
src/WebSocketsClient.cpp
src/WebSocketsNetworkClient.h
src/WebSocketsNetworkClientSecure.h

Why:
- Allow user-defined network interfaces to switch been WiFi and mobile modems during run-time
- Allow custom classes to be used as the network, ssl and server classes
This change addresses the need by:
- Creating a new custom WEBSOCKETS_NETWORK_TYPE that expects the user to set network classes
- WEBSOCKETS_NETWORK_CLASS
- WEBSOCKETS_NETWORK_SSL_CLASS
- WEBSOCKETS_NETWORK_SERVER_CLASS
Related issues: #779 #910

Allow definition of custom network interfaces
